### ISSUE TITLE
覆盖文件后会宝塔会紫铜修复

### ISSUE THREAD

**Issue by citongdongmai** [XOS/BTPanel_Crack#1]
覆盖文件后会宝塔会紫铜修复望锁定宝塔修复文件功能

**Comment by XOS** [comment]
> 覆盖文件后会宝塔会紫铜修复望锁定宝塔修复文件功能

更新后会覆盖破解文件，替换文件后需要给破解文件设置只读权限。每次更新新版本都要重新替换下的。

**Comment by citongdongmai** [comment]
还有部分插件无法使用





---原始邮件---
发件人: "翠花"<notifications@github.com&gt;
发送时间: 2020年9月25日(周五) 晚上6:33
收件人: "XOS/BTPanel_Crack"<BTPanel_Crack@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"citongdongmai"<q19889030@qq.com&gt;;
主题: Re: [XOS/BTPanel_Crack] 覆盖文件后会宝塔会紫铜修复 (#1)




  
覆盖文件后会宝塔会紫铜修复望锁定宝塔修复文件功能
  
更新后会覆盖破解文件，替换文件后需要给破解文件设置只读权限。每次更新新版本都要重新替换下的。
